# Optional Chaining 

> 옵셔널 타입의 값에 언래핑 없이 접근하기
> 

```swift
class Person {
    var residence: Residence?
}
class Residence {
    var numberOfRooms = 1
}

let john = Person() // residence == nil

//Force Unwrapping
let roomCount = john.residence!.numberOfRooms //runtime error

//Optional Chainig
if let roomCount = john.residence?.numberOfRooms {

} else {

}
```

- 옵셔널 체이닝을 통해 얻어진 값은 실패 가능성이 있기 때문에 항상 옵셔널 값으로 리턴된다.
    - `Int? , String?`

### Subscript에 옵셔널 체이닝 접근

```swift
var testScores = ["Dave": [86, 82, 84], "Bev": [79, 94, 81]]
testScores["Dave"]?[0] = 91
testScores["Bev"]?[0] += 1
testScores["Brian"]?[0] = 72 //Brain을 키로 가지는 값이 없어서 아무 일 없음
```

### 여러 수준의 옵셔널 체이닝 연결

- 모델 관계에서 옵셔널 체이닝을 통해 모델 내의 더 깊은 프로퍼티, 메서드 등에 접근할 수 있다.
이때, 여러 단계의 옵셔널 체이닝이 여러 옵셔널 값으로 적용되진 않는다.
    - `Int?` 값을 옵셔널 체이닝으로 접근한다 해서 `Int??` 이 되지 않는 다는 것
    
    ```swift
    let johnsAddress = Address()
    johnsAddress.buildingName = "The Larches"
    johnsAddress.street = "Laurel Street"
    john.residence?.address = johnsAddress
    
    if let johnsStreet = john.residence?.address?.street { //String?값 리턴
        print("John's street name is \(johnsStreet).")
    } else {
        print("Unable to retrieve the address.")
    }
    ```

# Error Handling

> 프로그램에서 발생하는 에러에 대응하고 회복하는 과정
> 

### 에러 처리 방법

- 에러를 던지는 함수를 호출한 함수에게 전달(propagate)
- `do-catch` 구문을 이용해 에러를 처리
- 옵셔널 값으로 에러를 처리
- 에러가 발생하지 않는다고 확신 (ex. 강제 언래핑)

```swift
func someThrowingFunction() throws { ... }

func someFunction() {
		do {
				try someThrowingFunction()
		} catch {
				//에러 처리 구문		
		}
}

func anotherFunction() throws {
		try someThrowingFunction()
}
```

```swift
func nourish(with item: String) throws {
    do {
        try vendingMachine.vend(itemNamed: item)
    } catch is VendingMachineError { //콤마(,)를 사용해서 나열하는 방법도 가능
        print("Couldn't buy that from the vending machine.")
    }
}
```

- `do-catch` 구문이 모든 에러를 캐치하지 않는다면, 원하는 에러 케이스를 명시해서 해당 에러들만 처리하고, 그 예외사항은 `throw` 할 수 있다.

```swift
let x = try? someThrowingFunction()

let y: Int?
do {
    y = try someThrowingFunction()
} catch {
    y = nil
}
```

- `try?` 함수가 에러를 던지지 않고 성공할 경우는 옵셔널 Int값, 실패한 경우는 nil을 가지게 된다.

# Concurrency
> 비동기적 동작을 수행
> 

프로그램에서 코드를 일시적으로 중단하고 다시 실행하면 UI 업데이트와 같은 짧은 작업을 진행하면서 네트워크를 통해 데이터를 가져오는 등의 긴 실행 작업을 계속할 수 있다.

### 비동기 함수 정의 & 호출

비동기 함수는 `throws`함수와 유사하게 괄호 뒤에 `async` 키워드를 작성하여 선언한다. 

```swift
func listPhotos(inGallery name: String) async -> [String] {
    let result = // ... some asynchronous networking code ...
    return result
}
```

- 비동기 & throw 함수라면 `async throws` 순서로 표시

비동기 메서드를 호출할때는 해당 메서드가 반환될때 까지 실행이 일시 중단되고, 중단될 가능성을 표시하기 위해 함수 호출 앞에 `await` 을 작성한다.

```swift
let photoNames = await listPhotos(inGallery: "Summer Vacation")
let sortedNames = photoNames.sorted()
let name = sortedNames[0]
let photo = await downloadPhoto(named: name)
show(photo)
```

### 비동기 시퀀스

위 예시에서 배열 전체를 기다렸던것과 달리 비동기 시퀀스를 사용하여 배열 한 요소릴 기다린다.

```swift
let handle = FileHandle.standardInput
for try await line in handle.bytes.lines {
    print(line)
}
```

- `AsyncSequence` 프로토콜을 채택하여 `for-await-in` 을 커스텀 타입에서 사용 가능

### 비동기 함수 병렬 호출

```swift
//#1
let firstPhoto = await downloadPhoto(named: photoNames[0])
let secondPhoto = await downloadPhoto(named: photoNames[1])
let thirdPhoto = await downloadPhoto(named: photoNames[2])

let photos = [firstPhoto, secondPhoto, thirdPhoto]
show(photos)

//#2
async let firstPhoto = downloadPhoto(named: photoNames[0])
async let secondPhoto = downloadPhoto(named: photoNames[1])
async let thirdPhoto = downloadPhoto(named: photoNames[2])

let photos = await [firstPhoto, secondPhoto, thirdPhoto]
show(photos)

```

- 첫번째 방식에서는 하나의 사진을 다운로드 할때까지 다음 다운로드 작업을 기다려야 한다. 그런데 두번째 사진 다운로드에 첫번째 사진이 필요로 하지 않으므로 아래와 같이 각 다운로드 과정을 비동기적으 만들어줄 수 있다.
    - throw 함수로 propagate하는 과정과 비슷한 느낌
- 세 변수를 사용하는 `photos` 변수에서는 비동기 코드의 리턴을 기다려야 하므로 `await` 명시
